Makefile.env:
	@. nideovim/make.d/scripts/Makefile.env.sh

config:
	@. nideovim/make.d/scripts/config.sh

clean: down
	@. nideovim/make.d/scripts/clean.sh

ps:
	@. nideovim/make.d/scripts/ps.sh

nuke: down_removes_volumes=yes
nuke:
	@. nideovim/make.d/scripts/down.sh
